### ISSUE TITLE
Missing timer header, incorrect paths

### ISSUE THREAD

**Issue by GiorgioGhisotti** [dlr1516/ars#1]
The file ars/src/thirdparty/Profiler.cpp attempts to include the following:
`#include <emotion/3rdparty/Profiler.h>`
however, I think what it actually wants is
`#include "ars/thirdparty/Profiler.h"`
(it won't compile with the original line)

The file ars/thirdparty/Profiler.h tries to include Timer.h
`#include <emotion/3rdparty/Timer.h>`
which doesn't exist in the repository (and I don't know what library "emotion" is); I got the library to compile by adding the Timer.h file from glarot3d repository but I don't know if that could cause any problems at runtime.

**Comment by dlr1516** [comment]
Thank you for the issue. I changed the Profiler with a new one that does not have suche dependencies. 
Hope this solve the problem.
